### ISSUE TITLE
Automatically bundle ts test files

### ISSUE THREAD

**Issue by timreichen** [caspervonb/sponsor#17]
Would be neat if one could run

```sh
sponsor test --headless --browser chrome test.ts
```
and it would bundle it up the ts file and then run the tests.

At the moment the cmd is pretty long
```sh
deno bundle --no-check test.ts > test.js && sponsor test --headless --browser chrome test.js
```

**Comment by caspervonb** [comment]
Any specific reason to prefer bundles? You need to go pretty far back to find a browser without module support and the server will compile each module to JavaScript.

**Comment by timreichen** [comment]
I wrote bundling because it was the easiest way as a workaround with deno bundle via cli, but it could be just compiling.

**Comment by caspervonb** [comment]
The server emits JavaScript for all specifiers, so this is already implemented?

**Comment by timreichen** [comment]
Yes, the command wasn't working because there was an error thrown and made it appear that sponsor froze. Closing.
