### ISSUE TITLE
run all tests in current and nested dir

### ISSUE THREAD

**Issue by timreichen** [caspervonb/sponsor#18]
Would be neat if one could run 
```sh
sponsor test --headless --browser chrome
```
and it would run all test.\* and \*_test.\* files in the current and nested dirs like `deno test` does.

**Comment by caspervonb** [comment]
That should be the current behaviour as we go on a recursive walk collecting the same specifiers as I used in Deno's test runner.

**Comment by caspervonb** [comment]
But #20 will resolve it for sure, as it lets deno do most of the work via a proxy.

**Comment by caspervonb** [comment]
Deno now actually runs the tests, I just proxy the test harness.

**Comment by timreichen** [comment]
So it does, awesome🎉
